apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: sani427/book-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
